# Dimensionality Reduction

## Data exploration

The data for this exercise can be accessed via this [link](http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/human1.txt)

The original data has been pre processed for this exercise.

```{r}
#' set wd

setwd("~/IODS2020/IODS-project/data")

human<-read.csv('human2.csv', header = TRUE, sep = ',')

dim(human)
str(human)
```



```{r}
library(ggplot2)
library(GGally)
library(corrplot)
library(dplyr)
library(tidyr)

ggpairs(human)
summary(human)

cor(human) %>% corrplot()
```




```{r}
#' non-standardized data
pca_human <- prcomp(human)


# draw a biplot of the principal component representation and the original variables
biplot(pca_human, choices = 1:2, cex = c(0.3,0.3), col = c("grey40", "deeppink2"))

```



```{r}
#' standard data
human_std <- scale(human)

#' pca of data_std
pca_stdHuman <- prcomp(human_std)

#'bi-plot
biplot(pca_stdHuman, choices = 1:2, cex = c(0.3,0.3), col = c("grey40", "deeppink2"))

```


```{r}
#' Factominer
library(FactoMineR)

data(tea)
dim(tea)
str(tea)
summary(tea)
colSums(is.na(tea))

# column names to keep in the dataset
#keep_columns <- c("Tea", "How", "how", "sugar", "where", "lunch")

# select the 'keep_columns' to create a new dataset
tea_time <- tea %>% dplyr::select(c("Tea", "How", "how", "sugar", "where", "lunch"))
#colnames(tea_time)
# look at the summaries and structure of the data
summary(tea_time)
str(tea_time)

# visualize the dataset
gather(tea_time) %>% ggplot(aes(value)) + geom_bar() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) + 
  facet_wrap("key", scales = "free") 

# multiple correspondence analysis
mca <- MCA(tea_time, graph = FALSE)

# summary of the model
summary(mca)

# visualize MCA
plot(mca, invisible=c("ind"))
```

